spring:
  application:
    name: ai-service
  threads:
    virtual:
      enabled: true
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GOOGLE_CLOUD_PROJECT_ID:smart-inventory-dev}
          location: ${GOOGLE_CLOUD_LOCATION:us-central1}
          model: ${VERTEX_GEMINI_MODEL:gemini-1.5-flash}
          chat:
            options:
              model: ${VERTEX_GEMINI_MODEL:gemini-1.5-flash}
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}