spring:
  application:
    name: import-service
  threads:
    virtual:
      enabled: true

server:
  port: ${SERVER_PORT:8085}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}

app:
  inventory:
    base-url: ${INVENTORY_API_BASE_URL:http://inventory-service:8081/api/v1}
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-in-production-32-bytes-minimum-key}
