spring:
  application:
    name: inventory-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/smart_inventory}
    username: ${SPRING_DATASOURCE_USERNAME:admin_user}
    password: ${SPRING_DATASOURCE_PASSWORD:secret_password_2026}
  jpa:
    hibernate:
      ddl-auto: update # Crea las tablas automáticamente si no existen
    show-sql: true
  threads:
    virtual:
      enabled: true # Vital para las llamadas de larga duración a la IA

server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

app:
  ai:
    analysis-url: ${AI_ANALYSIS_URL:http://localhost:8080/api/v1/ai/analyze-stock}
  security:
    jwt:
      secret: ${JWT_SECRET:smartinventory-very-secret-key-change-in-prod-2026-1234567890}
      expiration-ms: ${JWT_EXPIRATION_MS:86400000}

