spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/smart_inventory}
    username: ${SPRING_DATASOURCE_USERNAME:admin_user}
    password: ${SPRING_DATASOURCE_PASSWORD:change-me-db-password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  threads:
    virtual:
      enabled: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}

app:
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-in-production-32-bytes-minimum-key}
      expiration-ms: ${JWT_EXPIRATION_MS:86400000}
