spring:
  application:
    name: eureka-server
  threads:
    virtual:
      enabled: true # Activa Virtual Threads (Java 21)

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # No se registra a sí mismo
    fetch-registry: false       # No necesita buscar otros registros

